/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecipeformpageImport } from './routes/recipeformpage'
import { Route as RecipedetailspageImport } from './routes/recipedetailspage'
import { Route as IdImport } from './routes/$id'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RecipeformpageRoute = RecipeformpageImport.update({
  path: '/recipeformpage',
  getParentRoute: () => rootRoute,
} as any)

const RecipedetailspageRoute = RecipedetailspageImport.update({
  path: '/recipedetailspage',
  getParentRoute: () => rootRoute,
} as any)

const IdRoute = IdImport.update({
  path: '/$id',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$id': {
      id: '/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof IdImport
      parentRoute: typeof rootRoute
    }
    '/recipedetailspage': {
      id: '/recipedetailspage'
      path: '/recipedetailspage'
      fullPath: '/recipedetailspage'
      preLoaderRoute: typeof RecipedetailspageImport
      parentRoute: typeof rootRoute
    }
    '/recipeformpage': {
      id: '/recipeformpage'
      path: '/recipeformpage'
      fullPath: '/recipeformpage'
      preLoaderRoute: typeof RecipeformpageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  IdRoute,
  RecipedetailspageRoute,
  RecipeformpageRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$id",
        "/recipedetailspage",
        "/recipeformpage"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$id": {
      "filePath": "$id.tsx"
    },
    "/recipedetailspage": {
      "filePath": "recipedetailspage.tsx"
    },
    "/recipeformpage": {
      "filePath": "recipeformpage.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
